export const REGISTER_USER_BEGIN = 'REGISTER_USER_BEGIN'
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS'
export const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR'

export const LOGIN_USER_BEGIN = 'LOGIN_USER_BEGIN'
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS'
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR'

export const CREATE_TASK_BEGIN = 'CREATE_TASK_BEGIN'
export const CREATE_TASK_SUCCESS = 'CREATE_TASK_SUCCESS'
export const CREATE_TASK_ERROR = 'CREATE_TASK_ERROR'

export const GET_ALLTASKS_BEGIN = 'GET_ALLTASKS_BEGIN'
export const GET_ALLTASKS_SUCCESS = 'GET_ALLTASKS_SUCCESS'
export const GET_ALLTASKS_ERROR = 'GET_ALLTASKS_ERROR'

export const DELETE_ITEM_BEGIN = 'DELETE_ITEM_BEGIN'
export const DELETE_ITEM_SUCCESS = 'DELETE_ITEM_SUCCESS'
export const DELETE_ITEM_ERROR = 'DELETE_ITEM_ERROR'



export const EDIT_ITEM_BEGIN = 'EDIT_ITEM_BEGIN'
export const EDIT_ITEM_SUCCESS = 'EDIT_ITEM_SUCCESS'
export const EDIT_ITEM_ERROR = 'EDIT_ITEM_ERROR'